version: "3.9"

services:
  db:
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${SA_PASSWORD}" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    hostname: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    restart: always
   
  migration:
    container_name: migration
    build: 
      context: .
      dockerfile: src/client/NetCore.Migration/Dockerfile
    command: ["dotnet", "run", "-d", "-m", "-s", "-t"]
    depends_on: 
      db:
        condition: service_healthy     
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      
  api:
     container_name: api
     build: 
       context: .
       dockerfile: src/client/NetCore.Api/Dockerfile
     depends_on: 
      db:
        condition: service_healthy     
      migration:
        condition: service_completed_successfully
     ports:
       - 6000:80
       - 6001:443
     environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}
     volumes:
      - ~/.netcoreapi/https:/https:ro