version: '3.9'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: netcore-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=nM2ZvJm-H4eFisl
