version: "3.9"

services:
  netcore-db:
    hostname: netcore-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=nM2ZvJm-H4eFisl    
    ports:
      - "1433:1433"
    restart: unless-stopped
    
  redis:
    hostname: netcore-redis
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    command: redis-server --requirepass nM2ZvJm-H4eFisl
    restart: unless-stopped